# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
#    routing_loader: true
    body_listener: true
    format_listener:
        rules:
            - { path: ^/api/, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
            - { path: ^/, prefer_extension: true, fallback_format: html,  priorities: [ html ] }
#    exception:
#        enabled: true
    param_fetcher_listener: true
    view:
        view_response_listener:  'force'
        formats:
            json: true